### ISSUE TITLE
Unknown error on Polyjuice (not encountered in Rinkeby)

### ISSUE THREAD

**Issue by haxyz** [nervosnetwork/godwoken-polyjuice#81]
Hello Folks at Nervos,
some tests on a [solidity contract](https://github.com/haxyz/sisyphus-gamble-v1-core/blob/master/SisyphusGamble.sol#L57) run just fine on Rinkeby, but they time out on Polyjuice.

To reproduce the error feel free to use this repository: https://github.com/haxyz/sisyphus-gamble-v1-tests

### Full output on Polyjuice
```
haxyz@nervos-workstation:~/sisyphus-gamble-v1-tests$ node index.js Polyjuice
Using Polyjuice network
Checking Balance...
Checking WETH Balance...
Approving WETH usage...
Txn Hash: 0x3a231dc9c56b3035955361e937740eb41f1d83a6b7f5c4c5a95ba6a17a01dd3b
new Sisyphus Gamble...
Txn Hash: 0x6f1347259b24f932be7a0db8722f8a5d0f74ad16a2eb67d731395c1f424cfd4d
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (/home/haxyz/sisyphus-gamble-v1-tests/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at /home/haxyz/sisyphus-gamble-v1-tests/node_modules/web3-core-method/lib/index.js:416:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  receipt: undefined
}
```
### Full output on Rinkeby
```
haxyz@nervos-workstation:~/sisyphus-gamble-v1-tests$ node index.js Rinkeby
Using Rinkeby network
Checking Balance...
Checking WETH Balance...
Approving WETH usage...
Txn Hash: 0x1988cb483325f7bb02a799d0dcae8208cc81ec6bb1f167a285e2ec5c85cc2a60
new Sisyphus Gamble...
Txn Hash: 0x1397b58390992c4d7ac74ecee785c5492d21bf94e9d3464ff4bf82a2c987fa66
Getting Sisyphus Gamble Venues...
Approving WETH usage...
Txn Hash: 0x8a090b1aa792c5b65004fea2341f95eb701ab0937aa3a90be86b7b8805c1bece
Calling gamble...
Txn Hash: 0xf5e0bf3412f4e837ac04e985e5a1b802ff5ecd26a723023f0f612531f9e951c2
Claiming prize...
Txn Hash: 0x72c5f29a5e11d37539c9ac2eb41fb048ba37fb6f36dceb38bccc9cdcc2affd13
```

**Comment by RetricSu** [comment]
deploy contract: https://github.com/RetricSu/deploy-sisyphus-gamble 
scripts to run:  https://github.com/haxyz/sisyphus-gamble-v1-tests (needs to update with local env variable, maybe @haxyz  can give it an update aims for devnet?)

@Flouse

**Comment by haxyz** [comment]
So, what you're doing different in your deploy, is that you're deploying `SisyphusGamble` directly while i let `SisyphusGambleVenue` take care of everything.

**Comment by haxyz** [comment]
`SisyphusGambleVenue` is a contract factory, so once deployed any user just need to approve the amout to fund the created that is gonna be created and call `newSisyphusGamble`, and `SisyphusGambleVenue` deploys `SisyphusGamble` itself.

**Comment by haxyz** [comment]
Let me modify the tests so that I can deploy too.

**Comment by haxyz** [comment]
Which parameters would you like to control from commandline ( `node index.js -n=Rinkeby ...` ) and which form .env?
- rpc url
- network
- private key
- which contracts to deploy use with default values
- which to deploy from which bytecode
- ...

**Comment by haxyz** [comment]
Done, of course let me know if I forgot something!

To simplify deploying contracts on Polyjuice and Rinkeby I used a [testERC20](https://github.com/haxyz/sisyphus-gamble-v1-tests/blob/master/contracts/testERC20.sol)  instead of a erc20-proxy.. and the **error changed**. Of course it's still deploying fine on Rinkeby.

My take is that there are two errors:
- the first depends on using a proxy contract (tomorrow I'll add the possibility to deploy and use a erc20-proxy)
- the second probably depends on the usage of `selfdestruct` in `claimingPrize`

Follows the full output of this second error:
```
haxyz@nervos-workstation:~/sisyphus-gamble-v1-tests$ yarn start
yarn run v1.22.5
$ node -r dotenv/config index.js
Using Polyjuice network with default RPC URL
Checking Balance...
Deploying contract...
Txn Hash: 0xd6193094d500c78b60a41b42d355cb831c1dc2ea4dc42aab149006e0e9b8c1ed
Sisyphus gamble venues deployed on address: 0xC60ECb5FffF9379AedFA8B3F1E13588e28032d55
Deploying contract...
Txn Hash: 0x6520a951a138de0025b5ee747045879a465b07577b0b52c50b874ad7b632822d
TestERC20 on address: 0x86A23AD90139f58a354AD055879f720982e57491
Checking ERC20 Balance...
Approving ERC20 usage...
Txn Hash: 0xcff4ed5ce048e9cdc233852e84b7fb7e0113268cf3eef551a2283155829db08c
New Sisyphus Gamble...
Txn Hash: 0x75f8fcc4e9d252926d66383648a8cfc622aadaf87e736bc0578d377ae84ccbbf
Getting Sisyphus Gamble Venues...
Sisyphus gamble venues deployed on address: 0x86AE547922F4B0Ba2E96CB5f3ad2B7b7f63c8DF8
Approving ERC20 usage...
Txn Hash: 0x20b7d15a2444304ca6c6d2c4ed3a0ed859afa5e76d2d438c74bfc23bbe1a3d92
Calling gamble...
Txn Hash: 0x150a3310385da125fc718463d68107fbfc37f87c443bd07c5f21e80e3abb2b7d
Claiming prize...
Txn Hash: 0x83c2d81535b6db2ac8ecf9c40f7b87a6d8ff14e77926688d959892351bc23abb
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (/home/haxyz/sisyphus-gamble-v1-tests/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at /home/haxyz/sisyphus-gamble-v1-tests/node_modules/web3-core-method/lib/index.js:416:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  receipt: undefined
}
Done in 875.80s.
```

**Comment by Flouse** [comment]
### We should wait until enough blocks passed since the last gamble.
https://github.com/RetricSu/deploy-sisyphus-gamble/blob/a190a986f2/contracts/gamble.sol#L149

## Script
```
"strict mode"

const NETWORK = process.env.SGT_NETWORK;
if (NETWORK !== 'Polyjuice' && NETWORK !== 'Rinkeby') {
    throw "NETWORK environment variable must be either Polyjuice or Rinkeby";
}
console.log(`Using ${NETWORK} network with ${process.env.SGT_RPC_URL? process.env.SGT_RPC_URL:"default"} RPC URL`);

if (!process.env.SGT_ACCOUNT_PRIVATE_KEY) {
    throw "SGT_ACCOUNT_PRIVATE_KEY environment variable not set"
}

const {web3, DEFAULT_SEND_OPTIONS, account, ACCOUNT_POLY_ADDRESS} = require('./'+NETWORK);

async function checkBalance(amount) {
    console.log(`Checking Balance...`);

    const balance = BigInt(await web3.eth.getBalance(account.address));
    console.log("balance of", account.address, `= ${balance}`);

    if (balance < amount) {
        throw `Insufficient balance. Can't issue a smart contract call. Please deposit funds to your address: ${account.address}`;
    }
}

async function deploy(contractArtifact,arguments) {
    console.log(`Deploying contract...`);
    const tx = new web3.eth.Contract(contractArtifact.abi).deploy({
        data: contractArtifact.bytecode || contractArtifact.data.bytecode.object,
        arguments: arguments,
    }).send(
        {
            ...DEFAULT_SEND_OPTIONS,
            from: account.address,
        }
    );

    tx.on('transactionHash', hash => console.log(`Txn Hash: ${hash}`));

    return tx;
}

async function checkERC20Balance(contract, address, amount) {
    console.log(`Checking ERC20 Balance...`);
    const balance = BigInt(await contract.methods.balanceOf(address).call({
        from: account.address
    }));
    console.log(`ERC20 Balance of ${address}:`, balance);

    if (balance < amount) {
        throw `Insufficient ERC20 balance. Please deposit ERC20 funds to your Ethereum address: ${account.address}`;
    }
}

async function getSisyphusGambleVenues(contract) {
    console.log(`Getting Sisyphus Gamble Venues...`);
    return contract.methods.getSisyphusGambleVenues().call({
        from: account.address
    });
}

async function approve(contract,address,amount) {
    console.log(`Approving ERC20 usage...`);
    const tx = contract.methods.approve(address,amount).send(
        {
            ...DEFAULT_SEND_OPTIONS,
            from: account.address,
        }
    );

    tx.on('transactionHash', hash => console.log(`Txn Hash: ${hash}`));

    return tx;
}

async function newSisyphusGamble(SGVenuesContract, erc20Address, startingPrize, minGamble, weight, gamblingBlocks) {
    console.log(`New Sisyphus Gamble...`);
    const tx = SGVenuesContract.methods.newSisyphusGamble(erc20Address, startingPrize, minGamble, weight, gamblingBlocks).send(
        {
            ...DEFAULT_SEND_OPTIONS,
            from: account.address,
        }
    );

    tx.on('transactionHash', hash => console.log(`Txn Hash: ${hash}`));

    return tx;
}

async function gamble(contract, amount) {
    console.log(`Calling gamble...`);
    const tx = contract.methods.gamble(amount).send(
        {
            ...DEFAULT_SEND_OPTIONS,
            from: account.address,
        }
    );

    tx.on('transactionHash', hash => console.log(`Txn Hash: ${hash}`));

    return tx;
}

async function claimPrize(contract) {
    console.log(`Claiming prize...`);
    const tx = contract.methods.claimPrize().send(
        {
            ...DEFAULT_SEND_OPTIONS,
            from: account.address,
        }
    );

    tx.on('transactionHash', hash => console.log(`Txn Hash: ${hash}`));

    return tx;
}

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

async function waitForNextBlock() {
    let blockNumber = await web3.eth.getBlockNumber();
    console.log(`blockNumber = ${blockNumber}`);
    while (await web3.eth.getBlockNumber() <= blockNumber) {
        console.log(`  waiting for the next block...`);
        await sleep(6000);
    }
}

(async () => {
    try {
        const SISYPHUSGAMBLEVENUES_ARTIFACT = require("sisyphus-gamble-v1-core/artifacts/SisyphusGambleVenues");
        const SISYPHUSGAMBLE_ARTIFACT       = require("sisyphus-gamble-v1-core/artifacts/SisyphusGamble");
        const TESTERC20_ARTIFACT            = require("./artifacts/testERC20");
        
        await checkBalance(1);

        tx = await deploy(SISYPHUSGAMBLEVENUES_ARTIFACT,[]);
        const SISYPHUSGAMBLEVENUES_ADDRESS = tx._address;
        console.log(`Sisyphus gamble venues deployed on address: ${SISYPHUSGAMBLEVENUES_ADDRESS}`);
        const SGVenuesContract = new web3.eth.Contract(SISYPHUSGAMBLEVENUES_ARTIFACT.abi, SISYPHUSGAMBLEVENUES_ADDRESS);

        tx = await deploy(TESTERC20_ARTIFACT,[]);
        const ERC20_ADDRESS = tx._address;
        console.log(`TestERC20 on address: ${ERC20_ADDRESS}`);
        const ERC20Contract = new web3.eth.Contract(TESTERC20_ARTIFACT.abi, ERC20_ADDRESS);
        
        await waitForNextBlock();
        await checkERC20Balance(ERC20Contract, ACCOUNT_POLY_ADDRESS, 2);

        await approve(ERC20Contract, SISYPHUSGAMBLEVENUES_ADDRESS, 1);
        await newSisyphusGamble(SGVenuesContract, ERC20_ADDRESS, 1, 1, 1, 1);

        await waitForNextBlock();
        await checkERC20Balance(ERC20Contract, ACCOUNT_POLY_ADDRESS, 2);

        tx = await getSisyphusGambleVenues(SGVenuesContract);
        const SISYPHUSGAMBLE_ADDRESS = tx[0].sisyphusGamble;
        console.log(`Sisyphus gamble venues deployed on address: ${SISYPHUSGAMBLE_ADDRESS}`);

        const SGContract = new web3.eth.Contract(SISYPHUSGAMBLE_ARTIFACT.abi, SISYPHUSGAMBLE_ADDRESS);

        await approve(ERC20Contract, SISYPHUSGAMBLE_ADDRESS, 1);
        await gamble(SGContract, 1);

        await waitForNextBlock();
        await checkERC20Balance(ERC20Contract, ACCOUNT_POLY_ADDRESS, 2);

        await waitForNextBlock();
        await claimPrize(SGContract);
        await checkERC20Balance(ERC20Contract, ACCOUNT_POLY_ADDRESS, 2);
    } catch (error) {
        console.log(error);
    }
})();
```

## Logs


```log
$ node -r dotenv/config index.js
Using Polyjuice network with http://imagos:8024 RPC URL
Checking Balance...
balance of 0x44D6226d5d7c2b42523cf28A4EFC9E471e62Bb07 = 159983752328
balance of 0xD43ceeDb05Cb260123E9D683Db67D5306868b9E8 =  280000000000n
Deploying contract...
Txn Hash: 0x24ff0044f3cb8c8e004f4e623bb395f14d1d3b4790627b65b388a7a4a29b8eb9
Sisyphus gamble venues deployed on address: 0xfB9a83b9800b4d5cb6b981bee1435De9379c50cC
Deploying contract...
Txn Hash: 0x7ba4d543d778b2a35615eef28412939e34525a1fb5fdf4892a6e2e83d2491050
TestERC20 on address: 0x9e740B8a9Ca8E6C5F035D1c61B09ff7f1f4a070E
blockNumber = 8375
  waiting for the next block
  waiting for the next block
  waiting for the next block
  waiting for the next block
  waiting for the next block
  waiting for the next block
  waiting for the next block
Checking ERC20 Balance...
ERC20 Balance of 0x315a2160b5cbf24ee4f7aab0fb31926e1fb758de: 115792089237316195423570985008687907853269984665640564039457584007913129639935n
Approving ERC20 usage...
Txn Hash: 0xb526e3024abaa41fb79ce53c92303d54cdacac05b0ee25cd064b63c67937ac7f
New Sisyphus Gamble...
Txn Hash: 0xa6115767d567f85a99ca63722b81e386736277a0758c1f029848c40aba41cba6
blockNumber = 8376
  waiting for the next block
  waiting for the next block
  waiting for the next block
  waiting for the next block
Checking ERC20 Balance...
ERC20 Balance of 0x315a2160b5cbf24ee4f7aab0fb31926e1fb758de: 115792089237316195423570985008687907853269984665640564039457584007913129639934n
Getting Sisyphus Gamble Venues...
Sisyphus gamble venues deployed on address: 0x9920c79c976aB017b0510BCe4B797b8ebfAAA7Fd
Approving ERC20 usage...
Txn Hash: 0xfc7afffb684972271cbbefc1b99225812e1e4a3991b2824c0a81cf56c7c63223
Calling gamble...
Txn Hash: 0x2b36d3ba66ad54a1529206cf29240cc9c3bcc40884d91389d7bcd92c912155ce
blockNumber = 8377
  waiting for the next block
  waiting for the next block
  waiting for the next block
  waiting for the next block
Checking ERC20 Balance...
ERC20 Balance of 0x315a2160b5cbf24ee4f7aab0fb31926e1fb758de: 115792089237316195423570985008687907853269984665640564039457584007913129639933n
blockNumber = 8378
  waiting for the next block
  waiting for the next block
  waiting for the next block
  waiting for the next block
Claiming prize...
Txn Hash: 0x5c35a7bb29f485b05a3f1ad511b01ad584f766fecd2151d8e0c03d7f25d5e69d
Checking ERC20 Balance...
ERC20 Balance of 0x315a2160b5cbf24ee4f7aab0fb31926e1fb758de: 115792089237316195423570985008687907853269984665640564039457584007913129639935n
Done in 135.98s.
```

**Comment by haxyz** [comment]
I assumed (wrongly) that each call would be incorporated in a different block, good catch, thanks 👍

**Comment by haxyz** [comment]
Is the fork you provided the one you tested?

I noticed the output doesn't add up to your fork:
```
balance of 0x44D6226d5d7c2b42523cf28A4EFC9E471e62Bb07 = 159983752328
balance of 0xD43ceeDb05Cb260123E9D683Db67D5306868b9E8 =  280000000000n
```

**Comment by haxyz** [comment]
At any rate I see you included `sudt-cli` in `package.json`, have you already tested with it?

From the output I would assume No, so you used the testERC20 I provided, so the **first bug is still standing**, so I still have to integrate sudt proxy in the test.

**Comment by haxyz** [comment]
I added the possibility to use [already deployed contracts](https://github.com/haxyz/sisyphus-gamble-v1-tests/commit/0da4c49c7eb37e34780d9b41bd89c693c3458931) and **the first bug is still there**. 

By using the following `.env`, which uses a deployed ETH ERC20 Proxy Contract and an account on testnets which holds enough CKB and ETH:

```
SGT_ACCOUNT_PRIVATE_KEY=<YOUR-ETHEREUM-PRIVATE-KEY>
SGT_NETWORK=Polyjuice
SGT_ERC20_ADDRESS=0x659f945e59b11a4E2dd2AD62a934BeEe5436eAaf
```

Gives the follwing output:
```log
$ node -r dotenv/config index.js
Using Polyjuice network with default RPC URL
Checking Balance...
Balance of 0x9d23e5D38C31DF9FF11512e40f43a2a4Fa7a3b41 = 413499119510
Deploying contract...
Txn Hash: 0x2662e41a62429723fd0c015dd51987f4ae9176db4608394b6824e76ea36a5a02
Sisyphus gamble venues on address: 0x29AC42324A7bE16dcDe459b5F960eb9cbb7F0663
ERC20 on address: 0x659f945e59b11a4E2dd2AD62a934BeEe5436eAaf
blockNumber = 51190
  waiting for the next block...
  waiting for the next block...
  waiting for the next block...
  waiting for the next block...
  waiting for the next block...
  waiting for the next block...
  waiting for the next block...
Checking ERC20 Balance...
ERC20 Balance of 0x6a9729b13a39c948b5a47dc20be3282c03bf98dd = 999000000000000
Approving ERC20 usage...
Txn Hash: 0xb14bca58f08fa027740cb1c60a03bbba731f369810d0346315ceeecf4d5057c3
New Sisyphus Gamble...
Txn Hash: 0x9c2cc97d7c5e7ae8ea942a0a7db3008cf22694b1edb01fadd655683f1a46a767
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Object.TransactionError (/home/haxyz/sisyphus-gamble-v1-tests/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at /home/haxyz/sisyphus-gamble-v1-tests/node_modules/web3-core-method/lib/index.js:416:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  receipt: undefined
}
Done in 852.44s.
```

**Comment by haxyz** [comment]
P.S.: of course I tried running `godwoken kicker` but [without any luck so far. ](https://github.com/RetricSu/godwoken-kicker/issues/103)

**Comment by haxyz** [comment]
Closing as #82 is the evident cause of this bug.
